In [22]:
import cv2 as cv
import numpy as np

In [23]:
img = cv.imread('8.jpg')
cv.imshow('zzb', img)
key = cv.waitKey()
if key == 27:
    cv.destroyAllWindows()

In [3]:
#Gaussian Kernel Effect
g_img = cv.GaussianBlur(img, (7, 7), 5)  #img:图像 ， (7, 7)：高斯核大小 ， 5：方差
cv.imshow('gaussian_blurr_zzb', g_img)
key = cv.waitKey()
if key == 27:
    cv.destroyAllWindows()

In [4]:
#变大高斯核大小，图像更加模糊，平滑效果更加明显
g_img = cv.GaussianBlur(img, (17, 17), 5)
cv.imshow('gaussian_blur_zzb', g_img)
key = cv.waitKey()
if key == 27:
    cv.destroyAllWindows()

In [6]:
#图像更清晰，因为方差更小，高斯图像更加尖锐，中心点起的作用更大
g_img1 = cv.GaussianBlur(img, (17, 17), 5)
g_img2 = cv.GaussianBlur(img, (17, 17), 3)
cv.imshow('gaussian_blur_zzb1', g_img1)
cv.imshow('gaussian_blur_zzb2', g_img2)
key = cv.waitKey()
if key == 27:
    cv.destroyAllWindows()

In [8]:
#查看高斯核
kernel = cv.getGaussianKernel(7, 5)  #大小为7， 方差为5
print(kernel)
#高斯核是一维的，是为了将两个方向的卷积运算分开进行。有助于减少运算量，提升运算速度。

[[0.12895603]
 [0.14251846]
 [0.15133131]
 [0.1543884 ]
 [0.15133131]
 [0.14251846]
 [0.12895603]]


In [9]:
#查看高斯核分布高斯效果
g1_img = cv.GaussianBlur(img, (7, 7), 5)
g2_img = cv.sepFilter2D(img, -1, kernel, kernel)  #ori, depth, kernel_x, kernel_y
cv.imshow('gaussian_blur_zzb', g1_img)
cv.imshow('filter2d_blur_zzb', g2_img)
key = cv.waitKey()
if key == 27:
    cv.destroyAllWindows()

# 其余应用

In [38]:
# 2nd derivative : laplacian(双边滤波,双边缘效果)
kernel_lap = np.array([[0,1,0], [1,-4,1], [0,1,0]], np.float32)
lap_img = cv.filter2D(img, -1, kernel = kernel_lap)
cv.imshow('lap_zzb', lap_img)
key = cv.waitKey()
if key == 27:
    cv.destroyAllWindows()

In [37]:
#应用：图像锐化 = edge + ori
#app:sharpen
#图像+edge = 更锐利的图像，突出了边缘
kernel_sharpe = np.array([[0,1,0], [1,-3,1], [0,1,0]], np.float32)
lap_img = cv.filter2D(img, -1, kernel = kernel_sharpe)
cv.imshow('sharp_zzb', lap_img)
key = cv.waitKey()
if key == 27:
    cv.destroyAllWindows()


In [33]:
#上图做法不对，由于周围有4个1， 中间是-3， 所以虽然有边缘效果，但是周围的1会使得原kernel有滤波效果，使图像模糊
#解决方法：取kernel_lap相反数，再加上原图，这样来突出中间像素，效果类似于小方差的高斯
#所以即可突出边缘，又可以保持图像清晰
kernel_sharpe = np.array([[0,-1,0], [-1,5,-1], [0,-1,0]], np.float32)
lap_img = cv.filter2D(img, -1, kernel = kernel_sharpe)
cv.imshow('sharpe_zzb', lap_img)
key = cv.waitKey()
if key == 27:
    cv.destroyAllWindows()

In [40]:
#更凶猛的边缘效果
#不仅考虑x-y方向上的维度， 同时考虑对角线方向上的维度
kernel_sharpe = np.array([[-1,-1,-1],[-1,8,-1],[-1,-1,-1]],np.float32)
lap_img = cv.filter2D(img, -1, kernel = kernel_sharpe)
cv.imshow('sharpe_zzb', lap_img)
key = cv.waitKey()
if key == 27:
    cv.destroyAllWindows()

# 边缘

In [42]:
#x轴
edgex = np.array([[-1,-2,-1], [0,0,0], [1,2,1]], np.float32)
sharpx_img = cv.filter2D(img, -1, kernel = edgex)
cv.imshow('edge_x', sharpx_img)
#y轴
edgey = np.array([[-1,0,1], [-2,0,2],[-1,0,-1]], np.float32)
sharpy_img = cv.filter2D(img, -1, kernel = edgey)
cv.imshow('edge_y', sharpy_img)

key = cv.waitKey()
if key == 27:
    cv.destroyAllWindows()

# 角点

In [8]:
img = cv.imread('23.png')
cv.imshow('img', img)
    
img_gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
cv.imshow('gray_img', img_gray)
print(img_gray)


key = cv.waitKey()
if key == 27:
    cv.destroyAllWindows()

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [9]:
#cv.cornerHarris(img_gray, blocksize, ksize, k)
#img - 输入图像，应该是灰度和float32类型。
# blockSize - 考虑角点检测的邻域大小
# ksize - 使用的Sobel算子的孔径参数。
# k - 方程中的Harris检测器自由参数。

img_harris = cv.cornerHarris(img_gray, 2, 3, 0.05)
# cv.imshow('img_harris', img_harris)
# key = cv.waitKey()
# if key == 27:
#     cv.destroyAllWindows()
#展示不出来，原因是：1.float类型  2.img_harris本质上是每个pixel对于Harris函数的响应
print(img_harris)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [11]:
#为了将角点显示清楚，可以对角点进行膨胀操作
img_harris = cv.dilate(img_harris, None)

thres = 0.05 * np.max(img_harris)  #阈值设置,大于阈值的都认为是角点
img[img_harris > thres] = [0, 0, 0]  #角点设置为黑色
cv.imshow('img_harris', img)
key = cv.waitKey()
if key == 27:
    cv.destroyAllWindows()

# SIFT：Scale-Invariant Feature Transform

In [12]:
# 1.DoG
# 2.Scale-space Extrema Detection
# 3.Accurate keypois localization
# 4.Eliminating Edge Responses
# 5.Orientation Assignment
# 6.Keypoint Descripter

In [35]:
#sift.detect（）函数查找图像中的关键点。
#如果只想搜索图像的一部分，则可以传递蒙版。
#每个关键点都是一个特殊的结构，它有许多属性，如（x，y）坐标，有意义邻域的大小，指定方向的角度，指定关键点强度的响应等。

#cv2.drawKeyPoints（）函数，该函数在关键点的位置上绘制小圆圈。
#如果你向它传递一个标志cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS，它将绘制一个大小为keypoint的圆圈，它甚至会显示它的方向。见下面的例子。

In [31]:
img = cv.imread('8.jpg')
# create sift class创建SIFT对象
sift = cv.xfeatures2d.SIFT_create()
# detect SIFT 检测关键点
kp = sift.detect(img, None)   # 查找图像中的关键点，None for mask, 如果想要搜索图像的一部分可以传递mask
# compute SIFT descriptor 描述关键点
kp,des = sift.compute(img,kp)  #计算关键点描述符
print(des.shape)
img_sift = cv.drawKeypoints(img, kp, outImage = np.array([]), flags = cv.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
cv.imshow('zzb',img)
cv.imshow('zzb_sift', img_sift)
key = cv.waitKey()
if key == 27:
    cv.destroyAllWindows()

(276, 128)


In [34]:
img = cv.imread('8.jpg')
sift = cv.xfeatures2d.SIFT_create()
kp, des = sift.detectAndCompute(img, None)  #可以通过cv.detectAndCompute函数将关键点检测和描述一起完成
img_sift = cv.drawKeypoints(img, kp, outImage = np.array([]), flags = cv.DrawMatchesFlags_DRAW_RICH_KEYPOINTS) 
cv.imshow('img', img)
cv.imshow('img_sift', img_sift)
key = cv.waitKey()
if key == 27:
    cv.destroyAllWindows()